language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn eslint
deploy:
  # deploy develop to the staging environment
  - provider: script
    script:
    - yarn deploy
    skip_cleanup: true
    on:
      branch: feat/deployFromTravis
  # deploy master to production
  - provider: script
    script:
    - yarn deploy
    skip_cleanup: true
    on:
      branch: master
#