language: node_js
node_js:
  - stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn install
script:
  - yarn eslint
deploy:
  # deploy develop to the staging environment
  - provider: script
    script: now alias $(now build -t=$NOW_TOKEN --public) $URL_DEV -t=$NOW_TOKEN
    skip_cleanup: true
    on:
      branch: develop
  # deploy master to production
  - provider: script
    script: now alias $(now build -t=$NOW_TOKEN --public) $URL_PROD -t=$NOW_TOKEN
    skip_cleanup: true
    on:
      branch: master
