install:
  - yarn install
script:
  - yarn eslint

before_deploy:
   - yarn build
deploy:
  # deploy develop to the staging environment
  - provider: script
    skip_cleanup: true
    script: yarn deployDev
    on:
      branch: develop
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script: yarn deployProd
    on:
      branch: master
  # deploy develop from all feat/ branches to the staging environment
  - provider: script
    skip_cleanup: true
    script: yarn deployDev
    on:
      branch: feat*

